SELECT TOP (100) [Country]
      ,[Year]
      ,[Status]
      ,[Life expectancy ]
      ,[Adult Mortality]
      ,[infant deaths]
      ,[percentage expenditure]
      ,[Measles ]
      ,[ BMI ]
      ,[under-five deaths ]
      ,[Polio]
      ,[Diphtheria ]
      ,[ HIV AIDS]
      ,[GDP]
      ,[ thinness  1-19 years]
      ,[ thinness 5-9 years]
      ,[Schooling]
      ,[Row_ID]
  FROM [World_life_expectancy].[dbo].[World_life_expectancy]
